webtalk_init -webtalk_dir C:/Users/Steven Lee/OneDrive/Documents/EE-UY 4323/EE-UY-4323/adder/adder.sim/sim_1/behav/xsim.dir/adder_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Mar 22 00:01:43 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2015.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1412921" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210939032_0_0_520" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ae36745c-d5a0-4702-a5cb-12b388835951" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "24189fd1147449588981fcec2d521509" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7 CPU         950  @ 3.07GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3074 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "6.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "61 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.20_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "20552_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1240985586 -regid "210939032_0_0_520" -xml C:/Users/Steven Lee/OneDrive/Documents/EE-UY 4323/EE-UY-4323/adder/adder.sim/sim_1/behav/xsim.dir/adder_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Steven Lee/OneDrive/Documents/EE-UY 4323/EE-UY-4323/adder/adder.sim/sim_1/behav/xsim.dir/adder_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Steven Lee/OneDrive/Documents/EE-UY 4323/EE-UY-4323/adder/adder.sim/sim_1/behav/xsim.dir/adder_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
