# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a200tfbg676-2

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/stevenlee/Documents/control_unit/control_unit.cache/wt [current_project]
set_property parent.project_path C:/Users/stevenlee/Documents/control_unit/control_unit.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:ac701:part0:1.2 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_vhdl -library xil_defaultlib C:/Users/stevenlee/Documents/control_unit/control_unit.srcs/sources_1/new/control_unit.vhd
synth_design -top control_unit -part xc7a200tfbg676-2
write_checkpoint -noxdef control_unit.dcp
catch { report_utilization -file control_unit_utilization_synth.rpt -pb control_unit_utilization_synth.pb }
